version: '3'
services:
    mysql:
        image: mysql:8.2.0
        container_name: mysql-prefect
        environment:
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        ports:
            - 3306:3306
        volumes:
            - ./data_infra/mysql-db:/var/lib/mysql
        restart: unless-stopped